# Generated by Django 4.2.7 on 2023-11-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.IntegerField()),
                ('frontend', models.IntegerField()),
                ('game', models.IntegerField()),
                ('data', models.IntegerField()),
                ('security', models.IntegerField()),
            ],
        ),
    ]
